federation_version: =2.7.0
subgraphs:
    listings:
        routing_url: http://localhost:4000
        schema:
            file: ../listings/src/schema.graphql
    reviews:
        routing_url: http://localhost:4001
        schema:
            file: ../reviews/src/schema.graphql
